### ISSUE TITLE
Configs textbox showing

### ISSUE THREAD

**Issue by joshdeveraux** [Haoming02/sd-webui-tabs-extension#21] opened 2024-08-22 23:20 UTC
![TabsExtension](https://github.com/user-attachments/assets/3f11c483-77c4-49c4-9aa6-53f2cfa6beeb)

Here are my currently installed extensions (excluding the built-in Automatic1111 ones):

![TabsExtension-InstalledExtensions](https://github.com/user-attachments/assets/505b1891-b1e5-41d3-a06e-31b01de81cb4)

**Comment by Haoming02** [comment] 2024-08-23 01:34
And I was able to install all those in the configs... Ahhh, what is actually causing these... T-T

<p align="center"><img src="https://github.com/user-attachments/assets/acec7f37-2116-4d63-a21d-b70df9d8deb9"></p>

**Comment by Haoming02** [comment] 2024-08-23 01:37
Did you get any error popup when the Webui is loading btw?

**Comment by Haoming02** [comment] 2024-08-23 01:46
Still no error... IDK anymore... T-T

<p align="center"><img src="https://github.com/user-attachments/assets/5d8fa6ec-57db-4811-b1aa-509951d81e74"></p>

**Comment by joshdeveraux** [comment] 2024-08-24 03:52
It only seems to show up whenever I enable the tabs extension. When I disable it, the box disappears. I'm very new to Stable Diffusion, so I'm not 100% sure what's up :/

Here's what I get in the console window when I start up Stable Diffusion (if it helps):

> Already up to date.
> Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
> Version: v1.10.1
> Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
> Installing requirements
> [auto-sd-paint-ext] Commit hash: 93245c05fc82c70682663328acdd9edeaae91546
> [auto-sd-paint-ext] Auto-update disabled.
> Installing requirements for diffusers
> Installing pyyaml-include for Infinity Grid Script
> You are up to date with the most recent release.
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\a1111-sd-webui-lycoris':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\a1111-sd-webui-tagcomplete':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\adetailer':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\auto-sd-krita-ext-xl':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\clip-interrogator':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\facechain':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\multi-subject-render':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\OneButtonPrompt':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-dynamic-prompts':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-extension-system-info':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-infinity-grid-generator-script':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-3d-open-pose-editor':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-aspect-ratio-helper':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-controlnet':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-freeu':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-incantations':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-infinite-image-browsing':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-loractl':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-negpip':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-neutral-prompt':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-prompt-all-in-one':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-regional-prompter':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-tabs-extension':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd-webui-thumbnailizer':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\sd_delete_button':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\Stable-Diffusion-Webui-Civitai-Helper':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\stable-diffusion-webui-composable-lora':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\stable-diffusion-webui-Prompt_Generator':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\stable-diffusion-webui-wildcards':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\StyleSelectorXL':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\test_my_prompt':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\ultimate-upscale-for-automatic1111':
> Already up to date.
> 
> Pulled changes for repository in 'E:\Stable Diffusion\webui\extensions\wildcard-gallery':
> Already up to date.
> 
> Launching Web UI with arguments: --autolaunch --update-check --api --administrator --xformers --opt-sub-quad-attention --upcast-sampling --medvram --medvram-sdxl --disable-safe-unpickle --update-all-extensions --opt-split-attention --allow-code --gradio-img2img-tool color-sketch
> 
> Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
> [-] ADetailer initialized. version: 24.8.0, num models: 24
> ControlNet preprocessor location: E:\Stable Diffusion\webui\extensions\sd-webui-controlnet\annotator\downloads
> 2024-08-23 16:31:47,688 - ControlNet - INFO - ControlNet v1.1.455
> [sd-webui-freeu] Controlnet support: *enabled*
> sd-webui-prompt-all-in-one background API service started successfully.
> Thumbnailizer initialized
> Loading weights [1b8fca3fee] from E:\Stable Diffusion\webui\models\Stable-diffusion\Artistic\Samaritan 3d Cartoon - v40 SDXL.safetensors
> [LyCORIS]-WARNING: LyCORIS legacy extension is now loaded, if you don't expext to see this message, please disable this extension.
> CHv1.8.11: Set Proxy:
> Creating model from config: E:\Stable Diffusion\webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
> E:\Stable Diffusion\system\python\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
>   warnings.warn(
> 2024-08-23 16:31:55,445 - ControlNet - INFO - ControlNet UI callback registered.
> E:\Stable Diffusion\system\python\lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
>   deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
> *** Error executing callback ui_tabs_callback for E:\Stable Diffusion\webui\extensions\facechain\scripts\facechain_sdwebui.py
>     Traceback (most recent call last):
>       File "E:\Stable Diffusion\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
>         res += c.callback() or []
>       File "E:\Stable Diffusion\webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
>         import app
>       File "E:\Stable Diffusion\webui\extensions\facechain\app.py", line 16, in <module>
>         from facechain.inference_fact import GenPortrait
>       File "E:\Stable Diffusion\webui\extensions\facechain\facechain\inference_fact.py", line 20, in <module>
>         from modelscope.pipelines import pipeline
>       File "E:\Stable Diffusion\system\python\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
>         from .base import Pipeline
>       File "E:\Stable Diffusion\system\python\lib\site-packages\modelscope\pipelines\base.py", line 16, in <module>
>         from modelscope.msdatasets import MsDataset
>       File "E:\Stable Diffusion\system\python\lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
>         from modelscope.msdatasets.ms_dataset import MsDataset
>       File "E:\Stable Diffusion\system\python\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 9, in <module>
>         from datasets import Dataset, DatasetDict, IterableDataset, IterableDatasetDict
>     ModuleNotFoundError: No module named 'datasets'
> 
> ---
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> *** Error executing callback app_started_callback for E:\Stable Diffusion\webui\extensions\auto-sd-krita-ext-xl\scripts\main.py
>     Traceback (most recent call last):
>       File "E:\Stable Diffusion\webui\modules\script_callbacks.py", line 256, in app_started_callback
>         c.callback(demo, app)
>       File "E:\Stable Diffusion\webui\extensions\auto-sd-krita-ext-xl\scripts\main.py", line 43, in on_app_started
>         app.middleware("http")(app_encryption_middleware)
>       File "E:\Stable Diffusion\system\python\lib\site-packages\fastapi\applications.py", line 895, in decorator
>         self.add_middleware(BaseHTTPMiddleware, dispatch=func)
>       File "E:\Stable Diffusion\system\python\lib\site-packages\starlette\applications.py", line 139, in add_middleware
>         raise RuntimeError("Cannot add middleware after an application has started")
>     RuntimeError: Cannot add middleware after an application has started
> 
> ---
> IIB Database file has been successfully backed up to the backup folder.
> Startup time: 66.4s (prepare environment: 33.4s, import torch: 3.8s, import gradio: 0.9s, setup paths: 1.2s, initialize shared: 0.2s, other imports: 0.6s, list SD models: 0.1s, load scripts: 5.3s, create ui: 10.5s, gradio launch: 4.7s, add APIs: 1.9s, app_started_callback: 3.6s).
> Loading VAE weights specified in settings: E:\Stable Diffusion\webui\models\VAE\sdxlVAE.safetensors
> Applying attention optimization: xformers... done.

**Comment by Haoming02** [comment] 2024-08-24 19:02
There seems to be errors caused by `facechain` and  `auto-sd-krita-ext-xl`. Can you try fixing/disabling them first and see if the issue from this Extension still persists?

**Comment by joshdeveraux** [comment] 2024-08-24 19:47
Still there when I disabled both of those. Here's the updated info for you:

![Screenshot 2024-08-24 134512](https://github.com/user-attachments/assets/b9d70c02-c27c-4775-ab23-177d4f5fcc85)

![Screenshot 2024-08-24 134450](https://github.com/user-attachments/assets/a4105e50-4c90-464f-a849-1462473a0aa3)

Console output:

> Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
> Installing requirements
> Installing pyyaml-include for Infinity Grid Script
> You are up to date with the most recent release.
> 
> Launching Web UI with arguments: --autolaunch --update-check --api --administrator --xformers --opt-sub-quad-attention --upcast-sampling --medvram --medvram-sdxl --disable-safe-unpickle --update-all-extensions --opt-split-attention --allow-code --gradio-img2img-tool color-sketch
> 
> Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
> [-] ADetailer initialized. version: 24.8.0, num models: 24
> ControlNet preprocessor location: E:\Stable Diffusion\webui\extensions\sd-webui-controlnet\annotator\downloads
> 2024-08-24 13:42:53,505 - ControlNet - INFO - ControlNet v1.1.455
> [sd-webui-freeu] Controlnet support: *enabled*
> sd-webui-prompt-all-in-one background API service started successfully.
> Thumbnailizer initialized
> Loading weights [dda8c0514c] from E:\Stable Diffusion\webui\models\Stable-diffusion\Artistic\sdxlUnstableDiffusers_v11Rundiffusion.safetensors
> [LyCORIS]-WARNING: LyCORIS legacy extension is now loaded, if you don't expext to see this message, please disable this extension.
> CHv1.8.11: Set Proxy:
> Creating model from config: E:\Stable Diffusion\webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
> E:\Stable Diffusion\system\python\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
>   warnings.warn(
> 2024-08-24 13:43:02,164 - ControlNet - INFO - ControlNet UI callback registered.
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> IIB Database file has been successfully backed up to the backup folder.
> Startup time: 65.4s (prepare environment: 33.6s, import torch: 4.1s, import gradio: 1.1s, setup paths: 1.3s, initialize shared: 0.2s, other imports: 0.6s, list SD models: 0.2s, load scripts: 5.8s, create ui: 11.1s, gradio launch: 4.8s, add APIs: 1.8s, app_started_callback: 0.6s).
> Loading VAE weights specified in settings: E:\Stable Diffusion\webui\models\VAE\sdxlVAE.safetensors
> Applying attention optimization: xformers... done.
> Model loaded in 33.1s (load weights from disk: 4.2s, create model: 2.2s, apply weights to model: 3.4s, apply fp8: 10.0s, load VAE: 0.3s, load textual inversion embeddings: 12.1s, calculate empty prompt: 0.8s).
>

**Comment by LotusXue** [comment] 2024-08-25 03:11
delete the file ui-config.json and try again

**Comment by Haoming02** [comment] 2024-09-04 09:50
May I know if the issue still persists?

As the same issue seems to have been fixed for others in `#20`

**Comment by LindezaBlue** [comment] 2024-09-12 01:06
Issue persists again here too, Only I am unable to read the whole error.
![image](https://github.com/user-attachments/assets/457303c7-ffa1-40a1-8f55-aea46b898e49)

This happens even when I have ALL my extensions turned off/removed. Only ones I left are built in since that was standard.

**Comment by Haoming02** [comment] 2024-09-12 11:20
The full string is: Press `F12` to open the browser console, and see if you have something like:

<p align="center"><img src="https://github.com/user-attachments/assets/74586dd5-0931-4cfd-96a7-3fe36e556126"></p>

<hr>

Is this yet another case of ***#BlameGradio*** moment...

**Comment by Haoming02** [comment] 2024-09-23 04:04
I'll close this if no one bothers to answer anything then...

**Closed as completed** 2024-09-25 02:44 UTC
